### ISSUE TITLE
 This mode is only for dump and offset output, slow application operation is possible (network patch is still left) Traceback (most recent call last):

### ISSUE THREAD

**Issue by fyfyfy982** [Impact-I/reFlutter#191]
[1/2]? 2

 This mode is only for dump and offset output, slow application operation is possible (network patch is still left)
Traceback (most recent call last):
  File "d:\python3.7.7\lib\urllib\request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "d:\python3.7.7\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\python3.7.7\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "d:\python3.7.7\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "d:\python3.7.7\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "d:\python3.7.7\lib\http\client.py", line 966, in send
    self.connect()
  File "d:\python3.7.7\lib\http\client.py", line 1414, in connect
    super().connect()
  File "d:\python3.7.7\lib\http\client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "d:\python3.7.7\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "d:\python3.7.7\lib\socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python3.7.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python3.7.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python3.7.7\Scripts\reflutter.exe\__main__.py", line 7, in <module>
  File "d:\python3.7.7\lib\site-packages\src\__init__.py", line 360, in main
    extractZip(sys.argv[1])
  File "d:\python3.7.7\lib\site-packages\src\__init__.py", line 355, in extractZip
    replaceLibFlutter()
  File "d:\python3.7.7\lib\site-packages\src\__init__.py", line 178, in replaceLibFlutter
    checkHash()
  File "d:\python3.7.7\lib\site-packages\src\__init__.py", line 317, in checkHash
    resp = urlopen('https://raw.githubusercontent.com/Impact-I/reFlutter/main/enginehash.csv').read().decode('utf-8')
  File "d:\python3.7.7\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "d:\python3.7.7\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "d:\python3.7.7\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "d:\python3.7.7\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "d:\python3.7.7\lib\urllib\request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "d:\python3.7.7\lib\urllib\request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

C:\Users\fyfyfy>reflutter "C:\Users\fyfyfy\Documents\Tencent Files\928584916\FileRecv\MobileFile\jinxun.apk"

 Choose an option:

 1. Traffic monitoring and interception
 2. Display absolute code offset for functions

 [1/2]? 1
Traceback (most recent call last):
  File "d:\python3.7.7\lib\urllib\request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "d:\python3.7.7\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\python3.7.7\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "d:\python3.7.7\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "d:\python3.7.7\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "d:\python3.7.7\lib\http\client.py", line 966, in send
    self.connect()
  File "d:\python3.7.7\lib\http\client.py", line 1414, in connect
    super().connect()
  File "d:\python3.7.7\lib\http\client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "d:\python3.7.7\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "d:\python3.7.7\lib\socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python3.7.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python3.7.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python3.7.7\Scripts\reflutter.exe\__main__.py", line 7, in <module>
  File "d:\python3.7.7\lib\site-packages\src\__init__.py", line 360, in main
    extractZip(sys.argv[1])
  File "d:\python3.7.7\lib\site-packages\src\__init__.py", line 355, in extractZip
    replaceLibFlutter()
  File "d:\python3.7.7\lib\site-packages\src\__init__.py", line 178, in replaceLibFlutter
    checkHash()
  File "d:\python3.7.7\lib\site-packages\src\__init__.py", line 317, in checkHash
    resp = urlopen('https://raw.githubusercontent.com/Impact-I/reFlutter/main/enginehash.csv').read().decode('utf-8')
  File "d:\python3.7.7\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "d:\python3.7.7\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "d:\python3.7.7\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "d:\python3.7.7\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "d:\python3.7.7\lib\urllib\request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "d:\python3.7.7\lib\urllib\request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

**Comment by fyfyfy982** [comment]
两种模式都用不了，请问这个报错是为什么呢

**Comment by HuChundong** [comment]
> 两种模式都用不了，请问这个报错是为什么呢

挂代理

**Comment by fyfyfy982** [comment]
打包的时候也要挂代理吗，代理不是用来抓包的吗，不使用抓包要挂代理吗

**Comment by HuChundong** [comment]
> 打包的时候也要挂代理吗，代理不是用来抓包的吗，不使用抓包要挂代理吗

自己看报错信息，文件下载不下来。又不是所有的东西都已经在你本地了。还要去请求判断你的flutter版本的

**Comment by fyfyfy982** [comment]
好的，没懂你说的挂代理是挂本地代理还是梯子

**Comment by fyfyfy982** [comment]
好的，刚刚没懂你说的挂代理是挂本地代理还是梯子

**Comment by Impact-I** [comment]
@fyfyfy982 You have network problems. What is your SnasphotHash?

**Comment by fyfyfy982** [comment]
I find version_hash= adf563436d12ba0d50ea5beb7f3be1bb,download relese libflutter.so Repackage，is ok dump ,but Unable to enter app

**Comment by fyfyfy982** [comment]
I can find dump.dart,but  Unable to enter app

**Comment by Impact-I** [comment]
@fyfyfy982 v2 - https://github.com/Impact-I/reFlutter/releases/tag/android-v2-adf563436d12ba0d50ea5beb7f3be1bb
