### ISSUE TITLE
Problem with this engine hash b863200c37df4ed378042de11c4e9ff34e4e58c9

### ISSUE THREAD

**Issue by qolbudr** [Impact-I/reFlutter#251]
i try to reflutter an apk but it print 

waiting...
b863200c37df4ed378042de11c4e9ff34e4e58c9

and do nothing

try to use docker but it says error https://fuchsia.googlesource.com/third_party/harfbuzz/ not found

**Comment by jayluxferro** [comment]
@qolbudr , the snapshot hash is `c8562f0ee0ebc38ba217c7955956d1cb` and the engine hash is `b863200c37df4ed378042de11c4e9ff34e4e58c9`

You can try building it with the docker instructions; if only that engine still exists on the main flutter engine branch. It is a very old flutter engine.


```
git clone https://github.com/Impact-I/reFlutter && cd reFlutter
docker build -t reflutter -f Dockerfile .
```


```
docker run -it -v "$(pwd):/t" -e HASH_PATCH=c8562f0ee0ebc38ba217c7955956d1cb -e COMMIT=b863200c37df4ed378042de11c4e9ff34e4e58c9 reflutter
```

**Comment by qolbudr** [comment]
how do i know the flutter engine still exist?

**Comment by jayluxferro** [comment]
`https://github.com/flutter/engine/tree/[engine_commit_hash]`

Eg. https://github.com/flutter/engine/tree/b863200c37df4ed378042de11c4e9ff34e4e58c9

**Comment by qolbudr** [comment]
> @qolbudr , the snapshot hash is `c8562f0ee0ebc38ba217c7955956d1cb` and the engine hash is `b863200c37df4ed378042de11c4e9ff34e4e58c9`
> 
> You can try building it with the docker instructions; if only that engine still exists on the main flutter engine branch. It is a very old flutter engine.
> 
> ```
> git clone https://github.com/Impact-I/reFlutter && cd reFlutter
> docker build -t reflutter -f Dockerfile .
> ```
> 
> ```
> docker run -it -v "$(pwd):/t" -e HASH_PATCH=c8562f0ee0ebc38ba217c7955956d1cb -e COMMIT=b863200c37df4ed378042de11c4e9ff34e4e58c9 reflutter
> ```

tried this one but it shows error like this here the log

```
docker run -it -v "$(pwd):/t" -e HASH_PATCH=c8562f0ee0ebc38ba217c7955956d1cb -e COMMIT=b863200c37df4ed378042de11c4e9ff34e4e58c9 reflutter
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages
Processing /t
Installing collected packages: reflutter
  Running setup.py install for reflutter ... done
Successfully installed reflutter-0.7.7
Cloning into '/depot_tools'...
remote: Sending approximately 49.65 MiB ...
remote: Counting objects: 11, done
remote: Finding sources: 100% (11/11)
remote: Total 53975 (delta 36203), reused 53968 (delta 36203)
Receiving objects: 100% (53975/53975), 49.65 MiB | 34.03 MiB/s, done.
Resolving deltas: 100% (36203/36203), done.
Cloning into '/engine'...
remote: Enumerating objects: 753638, done.
remote: Counting objects: 100% (1094/1094), done.
remote: Compressing objects: 100% (483/483), done.
remote: Total 753638 (delta 727), reused 883 (delta 599), pack-reused 752544
Receiving objects: 100% (753638/753638), 646.11 MiB | 32.32 MiB/s, done.
Resolving deltas: 100% (571711/571711), done.
From https://github.com/flutter/engine
 * branch                  b863200c37df4ed378042de11c4e9ff34e4e58c9 -> FETCH_HEAD
HEAD is now at b863200c37 Cherry-picks for 1.9.1 (#12011)
USAGE:
reflutter your.(apk)|(ipa)
[main 9ce5b5854c] reflutter
 2 files changed, 55 insertions(+)
 create mode 100644 REFLUTTER
 create mode 100644 enginehash.csv
Updating depot_tools...
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress /engine /customEngine/src/_gclient_flutter_dpmkqp5p' in '/customEngine'
Cloning into '/customEngine/src/_gclient_flutter_dpmkqp5p'...
done.
Syncing projects: 100% ( 1/ 1) src/flutter
src/flutter (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00] 
[0:00:00] Finished running: git checkout --quiet refs/remotes/origin/main
[0:00:00] Finished running: git rev-parse --abbrev-ref=strict HEAD
[0:00:00] Checked out refs/remotes/origin/main to a detached HEAD. Before making any commits
in this repo, you should use 'git checkout <branch>' to switch 
to an existing branch or use 'git checkout origin -b <branch>' to
create a new branch for your work.
[0:00:00] Finished running: git -c core.quotePath=false ls-files
[0:00:00] 
[0:00:00] Finished running: git rev-parse --verify HEAD
[0:00:00] Finished running: git rev-parse HEAD
----------------------------------------
Traceback (most recent call last):
  File "/depot_tools/metrics.py", line 301, in print_notice_and_exit
    yield
  File "/depot_tools/gclient.py", line 3548, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/depot_tools/gclient.py", line 3534, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/depot_tools/gclient.py", line 3085, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/depot_tools/gclient.py", line 2041, in RunOnDeps
    work_queue.flush(revision_overrides,
  File "/depot_tools/gclient_utils.py", line 1016, in flush
    reraise(e[0], e[1], e[2])
  File "/depot_tools/gclient_utils.py", line 70, in reraise
    raise value
  File "/depot_tools/gclient_utils.py", line 1093, in run
    self.item.run(*self.args, **self.kwargs)
  File "/depot_tools/gclient.py", line 1076, in run
    self.ParseDepsFile()
  File "/depot_tools/gclient.py", line 788, in ParseDepsFile
    local_scope = gclient_eval.Parse(
  File "/depot_tools/gclient_eval.py", line 517, in Parse
    result = Exec(content, filename, vars_override, builtin_vars)
  File "/depot_tools/gclient_eval.py", line 423, in Exec
    value = _gclient_eval(node, filename, vars_dict)
  File "/depot_tools/gclient_eval.py", line 347, in _gclient_eval
    return _convert(node_or_string)
  File "/depot_tools/gclient_eval.py", line 290, in _convert
    raise ValueError(
ValueError: duplicate key in dictionary: src/third_party/dart/tools/sdks (file '/customEngine/src/flutter/DEPS', line 494)


```

**Comment by jayluxferro** [comment]
Most likely some of the dependencies in  `https://github.com/flutter/engine/blob/b863200c37df4ed378042de11c4e9ff34e4e58c9/DEPS` do not exist any longer so you can't build it.

**Comment by qolbudr** [comment]
so no more solution?

**Comment by jayluxferro** [comment]
I don't have any solution around it.

**Comment by bharatl13** [comment]
> https://github.com/flutter/engine/tree/

@jayluxferro can you help with new engine hash 33c7289e792b6d61aae02d2fe32e4cc5 ??

**Comment by Happ1ness-dev** [comment]
> so no more solution?

Hi, If you know the specific dependencies it misses, you could try looking for backups of them, maybe.

I remember trying to build some forge mods for old versions of Minecraft, and it was failing because the deps didn't exist anymore. 
I found the backup on web archive, fortunately. Maybe there are backups of this stuff too.

**Comment by jayluxferro** [comment]
> > https://github.com/flutter/engine/tree/
> 
> @jayluxferro can you help with new engine hash 33c7289e792b6d61aae02d2fe32e4cc5 ??

@bharatl13 , there's no engine hash like that.

Check all the flutter versions that have ever been released here: https://github.com/Impact-I/reFlutter/blob/main/scripts/enginehash.tmp.csv
