### ISSUE TITLE
Android Application crush

### ISSUE THREAD

**Issue by developerHUA** [Impact-I/reFlutter#280]
Hello, when I reflutter and sign [This Apk](https://www.123pan.com/s/SwbSVv-qI5jh.html) , the application crashed. Here are the crash logs.
Process: com.sjmly.sjmtask.xsh, PID: 2847
                                                                                                    java.lang.RuntimeException: Unable to get provider com.sjm.sjmdsp.core.utils.SjmDspFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:6552)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6094)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6003)
                                                                                                    	at android.app.ActivityThread.access$1100(ActivityThread.java:207)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1663)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6825)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                                                                                                    	at androidx.core.content.FileProvider.getFileProviderPathsMetaData(FileProvider.java:6)
                                                                                                    	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:4)
                                                                                                    	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:3)
                                                                                                    	at androidx.core.content.FileProvider.attachInfo(FileProvider.java:8)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:6547)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6094) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6003) 
                                                                                                    	at android.app.ActivityThread.access$1100(ActivityThread.java:207) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1663) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:193) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6825) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

**Comment by developerHUA** [comment]
This issue is due to the missing XML file in APK after refluxing.I need to know how to solve it. Thank you very much

**Comment by provsalt** [comment]
Ran into a similar issue. Looks like some XML are being lost when running on windows due to naming conflicts I believe. What solved it for me was using Linux when running reflutter.

**Comment by jayluxferro** [comment]
Same as #351 and #358 — app crash after engine replacement. Most common cause: engine version mismatch. Use `reflutter -n` (with no-interact) for newer engines, and verify the snapshot hash is in enginehash.csv. Also ensure you're using the correct architecture (`arm64-v8a` vs `armeabi-v7a`).
