### ISSUE TITLE
Reinforcement APK will collapse

### ISSUE THREAD

**Issue by newNiu13** [Impact-I/reFlutter#54]
2022-05-06 20:12:15.687 25561-25561/? E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/~~gNCysvKMM3GK1goWhUKB1w==/com.senyu.xiaofengling-1Uu7nl-WP96O5uJ4rI1ngQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~gNCysvKMM3GK1goWhUKB1w==/com.senyu.xiaofengling-1Uu7nl-WP96O5uJ4rI1ngQ==/lib/arm, /data/app/~~gNCysvKMM3GK1goWhUKB1w==/com.senyu.xiaofengling-1Uu7nl-WP96O5uJ4rI1ngQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:262)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:907)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:960)
        at android.app.LoadedApk.getResources(LoadedApk.java:1192)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2671)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6731)
        at android.app.ActivityThread.access$1400(ActivityThread.java:246)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7904)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
2022-05-06 20:12:15.709 4722-5478/? D/ActivityUtils: packageNameComponentInfo{com.senyu.xiaofengling/com.example.sd_reward.MainActivity}
2022-05-06 20:12:15.711 25561-25561/? W/yu.xiaofengling: type=1400 audit(0.0:4480): avc: granted { execute } for path="/data/data/com.senyu.xiaofengling/.jiagu/libjiagu.so" dev="sda32" ino=39843 scontext=u:r:untrusted_app:s0:c66,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c66,c257,c512,c768 tclass=file app=com.senyu.xiaofengling
2022-05-06 20:12:15.724 25561-25561/? I/TetheringManager: registerTetheringEventCallback:com.senyu.xiaofengling
2022-05-06 20:12:15.732 2968-4695/? W/TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.senyu.xiaofengling:getDeviceId:2
2022-05-06 20:12:15.721 25561-25561/? W/yu.xiaofengling: type=1400 audit(0.0:4481): avc: denied { read } for name="version" dev="proc" ino=4026532120 scontext=u:r:untrusted_app:s0:c66,c257,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=com.senyu.xiaofengling
2022-05-06 20:12:15.740 2968-4695/? W/TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.senyu.xiaofengling:getDeviceId:2

360jiagu.apk

**Comment by Impact-I** [comment]
Hello @newNiu13 

Thanks for your interest in the project!
Can you share the apk file?

**Comment by newNiu13** [comment]
> 你好@newNiu13
> 
> 感谢您对项目的关注！ 可以分享一下apk文件吗？

https://1drv.ms/u/s!Au-ZSrGn0XSbbjrnO6JGPnS8Raw?e=Do2Jsf

**Comment by Impact-I** [comment]
@newNiu13 
Are you using an emulator? 

Pay attention to supported architectures
`arm64, arm32;`

I see only one architecture in the apk file: `armeabi-v7a`
Do you have an apk file that can run on `arm64`?

**Comment by newNiu13** [comment]
> @newNiu13 你在用模拟器吗？
> 
> 注意支持的架构 `arm64, arm32;`
> 
> 我在 apk 文件中只看到一种架构：`armeabi-v7a` 您有可以在其上运行的 apk 文件`arm64`吗？

No, I didn't use the simulator

I use redmi K20

The reinforced APK cannot be opened after patching

**Comment by newNiu13** [comment]
> @newNiu13 你在用模拟器吗？
> 
> 注意支持的架构 `arm64, arm32;`
> 
> 我在 apk 文件中只看到一种架构：`armeabi-v7a` 您有可以在其上运行的 apk 文件`arm64`吗？

This application only supports aemeabi - + v7a, so it doesn't support reflurrry?

**Comment by Impact-I** [comment]
> This application only supports aemeabi - + v7a, so it doesn't support reflurrry?

In your case (redmi K20) Java is used
Flutter has nothing to do with it

What do you want to use reFlutter for?
Intercept function/Capture traffic ?

**Comment by newNiu13** [comment]
> 



> > This application only supports aemeabi - + v7a, so it doesn't support reflurrry?
> 
> In your case (redmi K20) Java is used Flutter has nothing to do with it
> 
> What do you want to use reFlutter for? Intercept function/Capture traffic ?



> > This application only supports aemeabi - + v7a, so it doesn't support reflurrry?
> 
> In your case (redmi K20) Java is used Flutter has nothing to do with it
> 
> What do you want to use reFlutter for? Intercept function/Capture traffic ?

I can use VPN proxy to intercept traffic and get traffic. I hope I can hook some algorithms

**Comment by Impact-I** [comment]
> > 
> 
> > > This application only supports aemeabi - + v7a, so it doesn't support reflurrry?
> > 
> > 
> > In your case (redmi K20) Java is used Flutter has nothing to do with it
> > What do you want to use reFlutter for? Intercept function/Capture traffic ?
> 
> > > This application only supports aemeabi - + v7a, so it doesn't support reflurrry?
> > 
> > 
> > In your case (redmi K20) Java is used Flutter has nothing to do with it
> > What do you want to use reFlutter for? Intercept function/Capture traffic ?
> 
> I can use VPN proxy to intercept traffic and get traffic. I hope I can hook some algorithms

I think they are in Java (Dex)
The file that you sent me does not contain a library for arm64

**Comment by newNiu13** [comment]
> > > 
> > 
> > 
> > > > This application only supports aemeabi - + v7a, so it doesn't support reflurrry?
> > > 
> > > 
> > > In your case (redmi K20) Java is used Flutter has nothing to do with it
> > > What do you want to use reFlutter for? Intercept function/Capture traffic ?
> > 
> > 
> > > > This application only supports aemeabi - + v7a, so it doesn't support reflurrry?
> > > 
> > > 
> > > In your case (redmi K20) Java is used Flutter has nothing to do with it
> > > What do you want to use reFlutter for? Intercept function/Capture traffic ?
> > 
> > 
> > I can use VPN proxy to intercept traffic and get traffic. I hope I can hook some algorithms
> 
> I think they are in Java (Dex) The file that you sent me does not contain a library for arm64

Because the application is not mine, I can't provide arm64. Will aemeabi be supported in the future?

**Comment by Impact-I** [comment]
> Because the application is not mine, I can't provide arm64. Will aemeabi be supported in the future?

It is already supported.
Your problem is not reFlutter

Try just re-signing the app - use only uber-apk-signer
The application will exit with the same error, this is probably an application integrity protection
Either the archive breaks when signing apk

**Comment by newNiu13** [comment]
> > Because the application is not mine, I can't provide arm64. Will aemeabi be supported in the future?
> 
> It is already supported. Your problem is not reFlutter
> 
> Try just re-signing the app - use only uber-apk-signer The application will exit with the same error, this is probably an application integrity protection Either the archive breaks when signing apk

I may not express very well. Can see it again? I packed it                  https://1drv.ms/u/s!Au-ZSrGn0XSbb6mMXTh8BHsZcok?e=U6wBuG

**Comment by Impact-I** [comment]
> I may not express very well. Can see it again? I packed it https://1drv.ms/u/s!Au-ZSrGn0XSbb6mMXTh8BHsZcok?e=U6wBuG

```
java -jar uber-apk-signer.jar --allowResign -a release.apk
adb install release-aligned-debugSigned.apk
```

Start App -> Crash App without use reFlutter

**Comment by newNiu13** [comment]
Thank you. I see
